version: "3.8"

services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    env_file:
      - ./configs/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./configs/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--port", "6379"]
